services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bodyfit
    ports:
    - "5432:5432"
    volumes:
      - bodyfit_data_dev:/var/lib/postgresql/data

volumes:
  bodyfit_data_dev: